name: Invoke marathon-cloud cli
description: Invoke marathon-cloud CLI in GitHub Actions
inputs:
  apiKey:
    description: "API key for authenticating with Marathon Cloud"
    required: true
  application:
    description: "Application binary path, e.g. apk file for Android or zip file of iOS Application"
    required: true
  testApplication:
    description: "Test application binary path, e.g. apk file for Android or zip file of iOS Test Runner app"
    required: true
  platform:
    description: "Testing platform. Android or iOS only"
    required: true
  osVersion:
    description: "Android or iOS OS version"
    required: false
  systemImage:
    description: "OS-specific system image. For Android one of [default,google_apis]. For iOS only [default]"
    required: false
  link:
    description: "Link to commit"
    required: false
  output:
    description: "Output folder"
    required: false
    default: "marathon"
  isolated:
    description: "Run each test in isolation, i.e. isolated batching"
    required: false
branding:
  icon: "play"
  color: "purple"
runs:
  using: "node16"
  main: "lib/index.js"
