name: Invoke marathon-cloud cli
description: Invoke marathon-cloud CLI in GitHub Actions
inputs:
  apiKey:
    description: "API key for authenticating with Marathon Cloud"
    required: true
  application:
    description: "Application binary path, e.g. apk file for Android or zip file of iOS Application"
    required: true
  testApplication:
    description: "Test application binary path, e.g. apk file for Android or zip file of iOS Test Runner app"
    required: true
  platform:
    description: "Testing platform. Android or iOS only"
    required: true
  osVersion:
    description: "Android or iOS OS version. For Android one of [10, 11, 12, 13, 14]. For iOS one of [16.4, 17.2]"
    required: false
  systemImage:
    description: "OS-specific system image. For Android one of [default,google_apis]. For iOS only [default]"
    required: false
  link:
    description: "Link to commit"
    required: false
  output:
    description: "Output folder for test run results"
    required: false
  outputGlob:
    description: "Only files matching this glob will be downloaded, i.e. 'tests/**' will download only the JUnit xml files"
    required: false
  isolated:
    description: "Run each test in isolation, i.e. isolated batching"
    required: false
  flavor:
    description: "Type of tests to run. Default: [native]. Possible values: [native, js-test-appium, python-robotframework-appium]"
    required: false
  filterFile:
    description: "File containing test filters in YAML format, following the schema described at https://docs.marathonlabs.io/runner/configuration/filtering/#filtering-logic. For iOS see also https://docs.marathonlabs.io/runner/next/ios#test-plans."
    required: false
  wait:
    description: "Wait for test run to finish if true, exits after triggering a run if false. Defaults to true"
    required: false
  name:
    description: "Name for run, for example it could be description of commit"
    required: false
  device:
    description: "Device type. For Android one of [phone, tv, watch]. For iOS one of [iPhone-14, iPhone-15]"
    required: false
  xcodeVersion:
    description: "Xcode version. Only for iOS. Possible values: [14.3.1, 15.2]"
    required: false
  xctestplanFilterFile:
    description: "Test filters supplied as .xctestplan file"
    required: false
  xctestplanTargetName:
    description: "Target name to use for test filtering in .xctestplan"
    required: false
  xctestrunEnv:
    description: "xctestrun environment variables, format: 'VAR1=VALUE1,VAR2=VALUE2'"
    required: false
  xctestrunTestEnv:
    description: "xctestrun testing environment variables, format: 'VAR1=VALUE1,VAR2=VALUE2'"
    required: false
  ignoreTestFailures:
    description: "When tests fail and this option is true then GHA will exit with code 0. By default, GHA will exit with code 1 in case of test failures and 0 for passing tests [possible values: true, false]"
    required: false
  pullFiles:
    description: "Pull files from devices after the test run. The format is 'ROOT1:PATH1,ROOT2:PATH2' where ROOT is one of [EXTERNAL_STORAGE, APP_DATA] and PATH is a relative path to the target file or directory. Example: EXTERNAL_STORAGE:Documents/some-results,APP_DATA:files/my_folder/some_file.txt. Note: Files with the same name and path from different devices may overwrite each other."
    required: false
branding:
  icon: "play"
  color: "purple"
runs:
  using: "node20"
  main: "lib/index.js"
