name: "CI Workflow"

on:
  workflow_dispatch:
  pull_request:

jobs:
  check_simple_android:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "16"

      - name: Setup Marathon Cloud
        uses: MarathonLabs/setup-marathon-cloud@2.0.1
        with:
          version: "1.0.30"

      - name: Run Marathon Cloud action-invoke
        uses: ./
        with:
          apiKey: ${{ secrets.RUN_TOKEN }}
          application: "example/app.apk"
          testApplication: "example/appTest.apk"
          platform: "android"
          name: "android_3_0_simple"

      - name: Show failure message
        if: failure()
        run: |
          echo "❌ Marathon Cloud action-invoke failed. Please check the following:"
          echo "1. Ensure that you have updated lib/index.js. See README for updating details."
          exit 1

  check_output_android:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "16"

      - name: Setup Marathon Cloud
        uses: MarathonLabs/setup-marathon-cloud@2.0.1
        with:
          version: "1.0.30"

      - name: Run Marathon Cloud action-invoke
        uses: ./
        with:
          apiKey: ${{ secrets.RUN_TOKEN }}
          application: "example/app.apk"
          testApplication: "example/appTest.apk"
          platform: "android"
          name: "android_3_0_output"
          output: "output"
          resultFile: "some-result.json"
          branch: "develop"

      - name: Check if output folder exists and is not empty
        run: |
          if [ -d "output" ] && [ "$(ls -A output)" ]; then
            echo "Output folder exists and is not empty."
          else
            echo "Output folder does not exist or is empty."
            exit 1
          fi

      - name: Upload artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: android_output
          path: output

      - name: Show failure message
        if: failure()
        run: |
          echo "❌ Marathon Cloud action-invoke failed. Please check the following:"
          echo "1. Ensure that you have updated lib/index.js. See README for updating details."
          exit 1

  check_output_failed_android:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "16"

      - name: Setup Marathon Cloud
        uses: MarathonLabs/setup-marathon-cloud@2.0.1
        with:
          version: "1.0.30"

      - name: Run Marathon Cloud action-invoke
        uses: ./
        with:
          apiKey: ${{ secrets.RUN_TOKEN }}
          application: "example/app.apk"
          testApplication: "example/appTestFailed.apk"
          platform: "android"
          name: "android_3_0_failed"
          output: "output"
          ignoreTestFailures: "true"

      - name: Check if output folder exists and is not empty
        run: |
          if [ -d "output" ] && [ "$(ls -A output)" ]; then
            echo "Output folder exists and is not empty."
          else
            echo "Output folder does not exist or is empty."
            exit 1
          fi

      - name: Upload artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: android_failed_output
          path: output

      - name: Show failure message
        if: failure()
        run: |
          echo "❌ Marathon Cloud action-invoke failed. Please check the following:"
          echo "1. Ensure that you have updated lib/index.js. See README for updating details."
          exit 1

  check_ios:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "16"

      - name: Setup Marathon Cloud
        uses: MarathonLabs/setup-marathon-cloud@2.0.1
        with:
          version: "1.0.30"

      - name: Run Marathon Cloud action-invoke
        uses: ./
        with:
          apiKey: ${{ secrets.RUN_TOKEN }}
          application: "example/sample.zip"
          testApplication: "example/sampleUITests-Runner.zip"
          platform: "ios"
          name: "ios_3_0"
          output: "output"

      - name: Check if output folder exists and is not empty
        run: |
          if [ -d "output" ] && [ "$(ls -A output)" ]; then
            echo "Output folder exists and is not empty."
          else
            echo "Output folder does not exist or is empty."
            exit 1
          fi

      - name: Upload artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: ios_output
          path: output

      - name: Show failure message
        if: failure()
        run: |
          echo "❌ Marathon Cloud action-invoke failed. Please check the following:"
          echo "1. Ensure that you have updated lib/index.js. See README for updating details."
          exit 1
